---
- name: remove default conf
  file: state=absent path=/etc/nginx/conf.d/default.conf

- name: add server main listener
  template: src=etc/nginx/conf.d/babar.conf dest=/etc/nginx/conf.d/babar.conf
  notify: restart-nginx

- name: nginx - update mime types
  copy: src=etc/nginx/mime.types dest=/etc/nginx/mime.types owner=root group=root mode=0644
  notify: restart-nginx
